### PR TITLE
Exported needs to be true

### PR DESCRIPTION
**Pull request by ayildirim**
I faced a problem sending intents into service. exported value must be true to allow sending intent to service from other apps

http://stackoverflow.com/questions/11410718/permission-issue-while-starting-a-service-from-android

### CODE REVIEW

**Comment by zagarolo** [comment]
Hi when no one can give you help solve ?
Il 13/apr/2015 19:14, "Ahmet YILDIRIM" <notifications@github.com> ha
scritto:

**Comment by frma71** [comment]
I've merged this, thanks ! I'll be back regarding cm11, I was actually thinking of skipping support for that now that cm12 is out !

**Comment by ayildirim** [comment]
Hi @frma71,

Do you have estimation, when you can publish new beta/alpha version with exported=true?

Thanks,

**Comment by frma71** [comment]
I'll build an alpha with exported=true tonight !

/F

**Comment by frma71** [comment]
Actually I built it right now, but I can't test it. Let me know if this
works.

/Fredrik

**Pull request merged**
